### ISSUE TITLE
add `page` to the list of accepted content item types

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-schemas#19]
- applies to newspaper issue schema
- it's necessary for newspaper without article-level segmentation (e.g. NZZ or Chronicling America)

**Comment by mromanello** [comment]
ping @e-maud @simon-clematide

**Comment by e-maud** [comment]
Ok for me. Just as a reminder, at the level of `content items` there is also the boolean `olr`.

**Comment by mromanello** [comment]
after discussing this we @e-maud we concluded that:
- this is a purely pragmatic solution
- but it would be desirable not to mix structural (e.g. image, page) and semantic content item types (e.g. article, crossword) within the same field.

As finding a solution to the latter would take considerable time (and possibly a discussion among many more people) I opened an issue for later: #20.
