### ISSUE TITLE
rethink content item types

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-schemas#20]
Content item types are currently found in two schemas:
- issue schema 
- content item schema

The controlled vocabulary currently contains the following values (i.e. types):
- article
- ad
- image
- table
- death_notice
- weather
- page

The problem (from a modelling perspective) is that structural types (e.g. page, image) are mixed with semantic ones (e.g. article, weather). A cleaner solution would be to separate the two by a more precise modelling.

**Comment by simon-clematide** [comment]
- Page, image, article are basic structural types that we always need for impresso modeling of content items. 
 - The distinction between ad and article can be made (but in the data it is also confused sometimes).
 -I agree that our semantic classes look a bit ad hoc.

**Comment by simon-clematide** [comment]
I suggest to keep this ad hoc classes for the time being and being pragmatic here. It is what would could do. In the future we could add a consistent formal classification (table, image, advertisement, service) and a more semantic IPTC classification (radio program, weather, politics...)
