### ISSUE TITLE
schema for iconographic material

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-schemas#5]
Objective: JSON schema to represent iconographic material of _impresso_ archives

First sketch:

**requirements:**
     - keep the link between illustration and associated article if present
     - keep good coordinates relatives to IIIF 
   
**which structure**:
     - same as per text rebuilt: one file per iconographic content item ('ici') ?
     - one file per issue, summarizing all `ici` per page ?

**basic info**
     - `ici` id
     - issue date
     - coordinates
     - versioning info
     - title or caption if available
     - link to related article

**Comment by mromanello** [comment]
I've done some thinking (and coding) on how to integrate information for iconographic material into our json schemas (in preparation of Benoit's work).

My conclusion is that the amount of information to store for each picture is very little, and IMO does not justify a serialization to a separate file (which would also somehow complicate data serialization). 

My suggestion would be to include picture information in the `issue.json` file, as we already do for other types of content items (ads, articles) -- see [example](https://raw.githubusercontent.com/impresso/impresso-schemas/master/examples/newspaper_issue/example0.json).

Picture would be yet another type of content items to be added to the field `i` of each issue JSON.

This is my tentative encoding of image-related infos (on Olive OCR data):

```json
{
    "l": {
      "id": "Pc03213",
      "res": "144",
      "path": "/32/Img/Pc0321300.jpg"
    },
    "c": [
      "454",
      "2002",
      "872",
      "2264"
    ],
    "m": {
      "id": "IMP-2012-10-19-a-i0276",
      "pp": [
        32
      ],
      "tp": "picture",
      "pOf": "IMP-2012-10-19-a-i0265"
    }
  }
```

where:
- `l` is the legacy section; contains legacy id (before we assign a new, canonical one), the resolution and path to image file in Olive's `Document.zip` file
- `m` > `pOf` indicates the article to which an image belongs (if any)
- `c` contains the image coordinates (still needing to be converted)

@simon-clematide @e-maud what do you think ?

**Comment by simon-clematide** [comment]
I agree with @mromanello and Occam's razor that the information does not need an extra file representation.
 I was thinking whether it would be useful to have a separate "counter" for image content items. So that from the content item id it would already be clear that it is not a textual entity. (maybe "IMP-2012-10-19-a-g0276")?
I would use the tp value "image" not "picture" (https://english.stackexchange.com/questions/65010/what-is-the-difference-between-image-picture-photograph-and-illustratio).
BTW, is there any notion of "caption" in the olive files?

**Comment by simon-clematide** [comment]
When looking at <https://impresso-project.ch/alpha/#/issue/IMP-2002-04-23-a/page/IMP-2002-04-23-a-p0001/article/IMP-2002-04-23-a-i0006>  (switch between TEXT and IMAGE  representation to see the effect), I was thinking whether there is any information on the the sequential ordering information  in the original data (Title comes first, then comes image, then comes article). 

Canonical data now
```
    {
      "c": [
        2995,
        2887,
        563,
        217
      ],
      "p": [
        {
          "l": [
            {
              "c": [
                3118,
                2868,
                355,
                111
              ],
              "t": [
                {
                  "c": [
                    3118,
                    2868,
                    355,
                    111
                  ],
                  "tx": "Vingt-cinq",
                  "s": 9
                }
              ]
            },
            {
              "c": [
                3060,
                2965,
                466,
                111
              ],
              "t": [
                {
                  "c": [
                    3060,
                    2965,
                    122,
                    111
                  ],
                  "tx": "ans",
                  "s": 9
                },
                {
                  "c": [
                    3203,
                    2965,
                    323,
                    111
                  ],
                  "tx": "fructueux",
                  "s": 9
                }
              ]
            }
          ]
        }
      ],
      "pOf": "IMP-2002-04-23-a-i0006"
    },
    {
      "c": [
        2995,
        2781,
        563,
        106
      ],
      "p": [
        {
          "l": [
            {
              "c": [
                3058,
                2820,
                459,
                44
              ],
              "t": [
                {
                  "c": [
                    3058,
                    2820,
                    42,
                    44
                  ],
                  "tx": "LA",
                  "s": 13
                },
                {
                  "c": [
                    3134,
                    2820,
                    383,
                    44
                  ],
                  "tx": "CHAUX-DE-FONDS",
                  "s": 13
                }
              ]
            }
          ]
        }
      ],
      "pOf": "IMP-2002-04-23-a-i0006"
    },
```

**Comment by mromanello** [comment]
thanks for your feedback @simon-clematide 

> 1. (maybe "IMP-2012-10-19-a-g0276")? ("g" as "i" and "p" are already taken). 

there are two reasons for sticking to the `i` prefix: 1) images are just another type of content item; 2) since we have to ensure the canonical ids won't change in the future, it's way easy/more manageable in the code to have a single way of numbering all content items.

> 2. I was thinking whether there is any information on the the sequential ordering information in the original data (Title comes first, then comes image, then comes article).

In the Olive data this information is somehow there but in such a cumbersome way that it makes it very hard to use/extract. In the BNL (mets/alto) data it's there and I'll find a way to keep it (perhaps putting an image placeholder/link in the page JSON).

**Comment by mromanello** [comment]
I forgot to address your point wrt to captions: yes, in some case there is and in other cases is missing ("Untitled picture") -- in Olive, and same in BNL as far as I've seen.

Current approach: I'm using `t` (`title`) as for articles/ads: if an image has a caption, and it's ≠ from 'Untitled picture' then it's kept in the `t` field.

**Comment by mromanello** [comment]
(I believe this can be closed as the issue JSON schema now covers also image content items).
